#!/bin/bash

# /etc/X11/xinit/xinitrc
# global xinitrc file, used by all X sessions started by xinit (startx)

export GTK2_RC_FILES="/etc/gtk-2.0/gtkrc"
/usr/bin/dwm &
cd /opt/nut/client/nutclient
#source /opt/nutenv/bin/activate
/opt/nutenv/bin/python ./client.py --fullscreen --halt_on_quit
sudo halt