#!/bin/sh

# /etc/X11/xinit/xinitrc
# global xinitrc file, used by all X sessions started by xinit (startx)

exec dwm &
cd /opt/nut/client/nutclient
source /opt/nutenv/bin/activate
/opt/nutenv/bin/python ./client.py --fullscreen
#TODO: uncomment halt, add shutdown param
#sudo halt